[build]
builder = "nixpacks"
buildCommand = "cd web && npm install && npm run build && cd ../api && python -m pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "cd api && python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[phases.setup]
nixPkgs = ["nodejs-18_x", "python39", "python39Packages.pip"]