[build]
builder = "nixpacks"
buildCommand = "cd web && npm install && npm run build && cd ../api && python -m pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --worker-class gevent -b 0.0.0.0:$PORT app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[phases.setup]
nixPkgs = ["nodejs-18_x", "python39", "python39Packages.pip"]

[variables]
NIXPACKS_NODE_VERSION = "18.17.0"
PORT = "8000"