[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 300

[variables]
PORT = "8000"
FLASK_APP = "api/app.py"
PYTHONUNBUFFERED = "1"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_PORT = "3000"

# App URLs
CONSOLE_API_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
CONSOLE_WEB_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
SERVICE_API_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
APP_WEB_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
FILES_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"

# Redis configuration (using Railway Redis plugin)
REDIS_HOST = "${{REDISHOST}}"
REDIS_PORT = "${{REDISPORT}}"
REDIS_PASSWORD = "${{REDISPASSWORD}}"
REDIS_USERNAME = "default"
REDIS_USE_SSL = "false"
REDIS_DB = "0"

# Generate a random secret key for sessions
SECRET_KEY = "${{RAILWAY_PRIVATE_KEY}}"