[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile"

[deploy]
startCommand = "/bin/bash -c 'source /app/api/venv/bin/activate && PYTHONPATH=/app/api exec gunicorn -c gunicorn_config.py app:app'"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Railway Volumes Configuration
[[volume]]
name = "dify-data"
mountPath = "/app/api/data"
size = "10Gi"

[[volume]]
name = "dify-storage"
mountPath = "/app/api/storage"
size = "10Gi"

[env]
RAILWAY_DOCKERFILE_PATH = "docker/Dockerfile"
VECTOR_DB_TYPE = "pgvector"
DEPLOY_ENV = "PRODUCTION"
DEBUG = "false"
FLASK_DEBUG = "0"
FLASK_ENV = "production"
CONSOLE_API_URL = "${RAILWAY_PUBLIC_DOMAIN}"
CONSOLE_WEB_URL = "${RAILWAY_PUBLIC_DOMAIN}"
SERVICE_API_URL = "${RAILWAY_PUBLIC_DOMAIN}"
APP_API_URL = "${RAILWAY_PUBLIC_DOMAIN}"
APP_WEB_URL = "${RAILWAY_PUBLIC_DOMAIN}"
FILES_URL = "${RAILWAY_PUBLIC_DOMAIN}"
PORT = "80"

# Database Configuration
DB_USERNAME = "${PGUSER}"
DB_PASSWORD = "${PGPASSWORD}"
DB_HOST = "${PGHOST}"
DB_PORT = "${PGPORT}"
DB_DATABASE = "${PGDATABASE}"

# Redis Configuration
REDIS_HOST = "${REDISHOST}"
REDIS_PORT = "${REDISPORT}"
REDIS_USERNAME = "${REDISUSER}"
REDIS_PASSWORD = "${REDISPASSWORD}"
REDIS_DB = "0"

# Vector Database (using pgvector)
PGVECTOR_HOST = "${PGHOST}"
PGVECTOR_PORT = "${PGPORT}"
PGVECTOR_USER = "${PGUSER}"
PGVECTOR_PASSWORD = "${PGPASSWORD}"
PGVECTOR_DATABASE = "${PGDATABASE}"

# Core Settings
SECRET_KEY = "your-secret-key"
INIT_PASSWORD = "password123"

# Server Configuration
SERVER_WORKER_AMOUNT = "2"
SERVER_WORKER_CLASS = "gevent"
GUNICORN_TIMEOUT = "360"

# Celery Configuration
CELERY_WORKER_CLASS = "gevent"
CELERY_WORKER_AMOUNT = "2"
MIGRATION_ENABLED = "true"

# Additional Environment Variables
FLASK_APP = "app.py"
SQLALCHEMY_DATABASE_URI = "sqlite:///instance/db.sqlite"
SESSION_TYPE = "filesystem"
SESSION_PERMANENT = "true"
SESSION_USE_SIGNER = "true"
CLEAN_UNFINISHED_INIT_MODEL_TASK = "true"
LOGGER_TYPE = "basic"
HOSTED_SETUP_COMPLETED = "true"
LOG_LEVEL = "DEBUG"
EDITION = "SELF_HOSTED"
TZ = "UTC"
