[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 300
startCommand = "/start.sh"
serverless = true

[variables]
# Service configuration
PORT = "8000"
FLASK_APP = "api/app.py"
PYTHONUNBUFFERED = "1"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_PORT = "3000"

# App URLs using Railway domain
CONSOLE_API_URL = "https://${{RAILWAY_SERVICE_NAME}}.${{RAILWAY_ENVIRONMENT_NAME}}.${{RAILWAY_PROJECT_NAME}}.railway.app"
CONSOLE_WEB_URL = "https://${{RAILWAY_SERVICE_NAME}}.${{RAILWAY_ENVIRONMENT_NAME}}.${{RAILWAY_PROJECT_NAME}}.railway.app"
SERVICE_API_URL = "https://${{RAILWAY_SERVICE_NAME}}.${{RAILWAY_ENVIRONMENT_NAME}}.${{RAILWAY_PROJECT_NAME}}.railway.app"
APP_WEB_URL = "https://${{RAILWAY_SERVICE_NAME}}.${{RAILWAY_ENVIRONMENT_NAME}}.${{RAILWAY_PROJECT_NAME}}.railway.app"
FILES_URL = "https://${{RAILWAY_SERVICE_NAME}}.${{RAILWAY_ENVIRONMENT_NAME}}.${{RAILWAY_PROJECT_NAME}}.railway.app"

# Database configuration (using references to toys-postgres service)
DATABASE_URL = "${{toys-postgres.DATABASE_URL}}"
PGHOST = "${{toys-postgres.PGHOST}}"
PGPORT = "${{toys-postgres.PGPORT}}"
PGDATABASE = "${{toys-postgres.PGDATABASE}}"
PGUSER = "${{toys-postgres.PGUSER}}"
PGPASSWORD = "${{toys-postgres.PGPASSWORD}}"

# Redis configuration (using Railway Redis plugin)
REDIS_HOST = "${{REDISHOST}}"
REDIS_PORT = "${{REDISPORT}}"
REDIS_PASSWORD = "${{REDISPASSWORD}}"
REDIS_USERNAME = "default"
REDIS_USE_SSL = "false"
REDIS_DB = "0"

# Generate a random secret key for sessions
SECRET_KEY = "${{RAILWAY_PRIVATE_KEY}}"