[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 300

[variables]
PORT = "8000"
NODE_ENV = "production"
HOSTNAME = "0.0.0.0"
RAILWAY_PUBLIC_DOMAIN = "true"